name: goodbytes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - pip
  - transformers
  - bs4
  - nltk
  - inflect
  - mlxtend
  - sentencepiece
  - pip:
    - accelerate